-- MySQL Script generated by MySQL Workbench
-- Mon 28 Oct 2019 03:50:25 PM MDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema messageTreeDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `messageTreeDB` ;

-- -----------------------------------------------------
-- Schema messageTreeDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `messageTreeDB` DEFAULT CHARACTER SET latin1 ;
USE `messageTreeDB` ;

-- -----------------------------------------------------
-- Table `messageTreeDB`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messageTreeDB`.`message` ;

CREATE TABLE IF NOT EXISTS `messageTreeDB`.`message` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NOT NULL,
  `parentID` INT(11) NULL DEFAULT NULL,
  `likes` INT(11) NULL DEFAULT '0',
  `timestamp` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
